# Analyse Exploratoire des Données (EDA)
## US Accidents (2016–2023)

Ce notebook présente la phase d’exploration et de nettoyage du dataset US-Accidents.
L’objectif est de comprendre la structure des données, identifier les problèmes de qualité
et préparer les variables pour les analyses statistiques avancées.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

plt.style.use("default")

Chargement INTELLIGENT du dataset (CRUCIAL ⚠️)

In [4]:
import pandas as pd
import numpy as np

# Colonnes à charger
cols = [
    "Severity",
    "Start_Time",
    "End_Time",
    "State",
    "City",
    "Weather_Condition",
    "Visibility(mi)",
    "Temperature(F)",
    "Wind_Speed(mph)",
    "Precipitation(in)"
]

# Chargement du CSV
df = pd.read_csv(
    "C:/Users/pc/Desktop/data/Analyse Statistique/StatistiqueAvancee/data/raw/US_Accidents.csv",
    usecols=cols,
    parse_dates=["Start_Time", "End_Time"],
    low_memory=False
)

# Vérification
df.head()

,Severity,Start_Time,End_Time,City,State,Temperature(F),Visibility(mi),Wind_Speed(mph),Precipitation(in),Weather_Condition
0,3,2016-02-08 05:46:00,2016-02-08 11:00:00,Dayton,OH,36.9,10.0,NaN,0.02,Light Rain
1,2,2016-02-08 06:07:59,2016-02-08 06:37:59,Reynoldsburg,OH,37.9,10.0,NaN,0.00,Light Rain
2,2,2016-02-08 06:49:27,2016-02-08 07:19:27,Williamsburg,OH,36.0,10.0,3.5,NaN,Overcast
3,3,2016-02-08 07:23:34,2016-02-08 07:53:34,Dayton,OH,35.1,9.0,4.6,NaN,Mostly Cloudy
4,2,2016-02-08 07:39:07,2016-02-08 08:09:07,Dayton,OH,36.0,6.0,3.5,NaN,Mostly Cloudy

In [13]:
df["Start_Time"] = pd.to_datetime(df["Start_Time"], errors="coerce")
df["End_Time"] = pd.to_datetime(df["End_Time"], errors="coerce")

In [ ]:
df.dtypes

Severity                      int64
Start_Time           datetime64[ns]
End_Time             datetime64[ns]
City                         object
State                        object
Temperature(F)              float64
Visibility(mi)              float64
Wind_Speed(mph)             float64
Precipitation(in)           float64
Weather_Condition            object
dtype: object

Aperçu général

Le dataset contient plusieurs millions de lignes avec des variables temporelles,
géographiques et météorologiques. Certaines colonnes présentent des valeurs manquantes,
notamment les variables météo.

In [38]:
df.head()

,Severity,Start_Time,End_Time,City,State,Temperature(F),Visibility(mi),Wind_Speed(mph),Precipitation(in),Weather_Condition
0,3,2016-02-08 05:46:00,2016-02-08 11:00:00,Dayton,OH,36.9,10.0,NaN,0.02,Light Rain
1,2,2016-02-08 06:07:59,2016-02-08 06:37:59,Reynoldsburg,OH,37.9,10.0,NaN,0.00,Light Rain
2,2,2016-02-08 06:49:27,2016-02-08 07:19:27,Williamsburg,OH,36.0,10.0,3.5,NaN,Overcast
3,3,2016-02-08 07:23:34,2016-02-08 07:53:34,Dayton,OH,35.1,9.0,4.6,NaN,Mostly Cloudy
4,2,2016-02-08 07:39:07,2016-02-08 08:09:07,Dayton,OH,36.0,6.0,3.5,NaN,Mostly Cloudy

In [15]:
df.shape

(7728394, 10)

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7728394 entries, 0 to 7728393
Data columns (total 10 columns):
 #   Column             Dtype
---  ------             -----
 0   Severity           int64
 1   Start_Time         datetime64[ns]
 2   End_Time           datetime64[ns]
 3   City               object
 4   State              object
 5   Temperature(F)     float64
 6   Visibility(mi)     float64
 7   Wind_Speed(mph)    float64
 8   Precipitation(in)  float64
 9   Weather_Condition  object
dtypes: datetime64[ns](2), float64(4), int64(1), object(3)
memory usage: 589.6+ MB

Valeurs manquantes

Les variables météorologiques présentent un taux de valeurs manquantes significatif,
ce qui nécessite une stratégie de traitement adaptée (imputation ou exclusion ciblée).

In [17]:
missing = df.isna().mean().sort_values(ascending=False) * 100
missing

Start_Time           9.616047
End_Time             9.616047
Weather_Condition    2.244438
City                 0.003274
Severity             0.000000
State                0.000000
Temperature(F)       0.000000
Visibility(mi)       0.000000
Wind_Speed(mph)      0.000000
Precipitation(in)    0.000000
dtype: float64

Nettoyage de base

In [18]:
# Suppression des lignes sans date
df = df.dropna(subset=["Start_Time", "End_Time"])

# Remplacement des valeurs manquantes météo par la médiane
for col in ["Visibility(mi)", "Temperature(F)", "Wind_Speed(mph)", "Precipitation(in)"]:
    df[col] = df[col].fillna(df[col].median())

Feature Engineering (IMPORTANT)

Des variables temporelles ont été créées afin d’analyser les patterns horaires,
hebdomadaires et saisonniers des accidents.

In [7]:
df["hour"] = df["Start_Time"].dt.hour
df["day_of_week"] = df["Start_Time"].dt.day_name()
df["month"] = df["Start_Time"].dt.month
df["is_weekend"] = df["Start_Time"].dt.weekday >= 5

AttributeError: Can only use .dt accessor with datetimelike values

In [19]:
#Vérification
df.dtypes

Severity                      int64
Start_Time           datetime64[ns]
End_Time             datetime64[ns]
City                         object
State                        object
Temperature(F)              float64
Visibility(mi)              float64
Wind_Speed(mph)             float64
Precipitation(in)           float64
Weather_Condition            object
dtype: object

In [54]:
#Valide Code Pour Feature Engineering
df["hour"] = df["Start_Time"].dt.hour
df["day_of_week"] = df["Start_Time"].dt.day_name()
df["month"] = df["Start_Time"].dt.month
df["is_weekend"] = df["Start_Time"].dt.weekday >= 5
df["Start_Time"] = pd.to_datetime(df["Start_Time"], errors="coerce")
df["End_Time"] = pd.to_datetime(df["End_Time"], errors="coerce")

## Sauvegarde des données nettoyées

In [ ]:
df.to_csv("../data/processed/us_accidents_clean.csv", index=False)
print("Fichier sauvegardé avec succès.")

Fichier sauvegardé avec succès.